# -*- coding: utf-8 -*-
"""Script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Kn3rVnlF36qOjvCMOj7luavJo5lKLkF

# Central Tendency for Housing Data
In this project, we will find the mean, median, and mode cost of one-bedroom apartments in three of the five New York City boroughs: Brooklyn, Manhattan, and Queens.

Using our findings, we will make conclusions about the cost of living in each of the boroughs. We will also discuss an important assumption that we make when we point out differences between the boroughs.

We worked with [Streeteasy.com](https://streeteasy.com/) to collect this data. While we will only focus on the cost of one-bedroom apartments, the dataset includes a lot more information if you’re interested in asking your own questions about the Brooklyn, Manhattan, and Queens housing market.
"""

# Commented out IPython magic to ensure Python compatibility.
# Import packages
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot as plt
# %matplotlib inline

# Read in housing data
brooklyn_one_bed = pd.read_csv('brooklyn-one-bed.csv')
brooklyn_price = brooklyn_one_bed['rent']

manhattan_one_bed = pd.read_csv('manhattan-one-bed.csv')
manhattan_price = manhattan_one_bed['rent']

queens_one_bed = pd.read_csv('queens-one-bed.csv')
queens_price = queens_one_bed['rent']

#As dataset for all places looks like same. so we are olny inspecting brooklyn dataset.
brooklyn_one_bed.head()

brooklyn_price.head()

# Add mean calculations below 
brooklyn_mean = np.average(brooklyn_price)
manhattan_mean = np.average(manhattan_price)
queens_mean = np.average(queens_price)

# Add median calculations below
brooklyn_median = np.median(brooklyn_price)
manhattan_median = np.median(manhattan_price)
queens_median = np.median(queens_price)

# Add mode calculations below
brooklyn_mode = stats.mode(brooklyn_price)
manhattan_mode = stats.mode(manhattan_price)
queens_mode = stats.mode(queens_price)

# Mean
try:
    print("The mean price in Brooklyn is " + str(round(brooklyn_mean, 2)))
except NameError:
    print("The mean price in Brooklyn is not yet defined.")
try:
    print("The mean price in Manhattan is " + str(round(manhattan_mean, 2)))
except NameError:
    print("The mean in Manhattan is not yet defined.")
try:
    print("The mean price in Queens is " + str(round(queens_mean, 2)))
except NameError:
    print("The mean price in Queens is not yet defined.")

# Median
try:
    print("The median price in Brooklyn is " + str(brooklyn_median))
except NameError:
    print("The median price in Brooklyn is not yet defined.")
try:
    print("The median price in Manhattan is " + str(manhattan_median))
except NameError:
    print("The median price in Manhattan is not yet defined.")
try:
    print("The median price in Queens is " + str(queens_median))
except NameError:
    print("The median price in Queens is not yet defined.")

#Mode
try:
    print("The mode price in Brooklyn is " + str(brooklyn_mode[0][0]) + " and it appears " + str(brooklyn_mode[1][0]) + " times out of " + str(len(brooklyn_price)))
except NameError:
    print("The mode price in Brooklyn is not yet defined.")
try:
    print("The mode price in Manhattan is " + str(manhattan_mode[0][0]) + " and it appears " + str(manhattan_mode[1][0]) + " times out of " + str(len(manhattan_price)))
except NameError:
    print("The mode price in Manhattan is not yet defined.")
try:
    print("The mode price in Queens is " + str(queens_mode[0][0]) + " and it appears " + str(queens_mode[1][0]) + " times out of " + str(len(queens_price)))
except NameError:
    print("The mode price in Queens is not yet defined.")

b_mode = 2500
m_mode = 3500
q_mode = 1750

"""We don’t find the mean, median, and mode of a dataset for the sake of it.

The point is to make inferences from our data. What can you say about the housing prices in Brooklyn, Queens, and Manhattan? Besides, “It’s really expensive to live in any of them.”

It looks like the average cost of one-bedroom apartments in Manhattan is the most, and in Queens is the least. This pattern holds for the median and mode values as well.

While the mode is not the most important indicator of centrality, the fact that mean, median, and mode are within a few hundred dollars for each borough indicates the data is centered around:

*  $3,300 for Brooklyn

*  $3,900 for Manhattan


*  $2,300 for Queens
"""

# Plot the figure
plt.hist(brooklyn_price, range=(0, 10000),  edgecolor='black')
plt.title("Brooklyn 1 Bedroom Price")
plt.xlabel("Cost")
plt.ylabel("Count")
plt.axvline(brooklyn_mean, color='r', linestyle='solid', linewidth=2, label="mean")
plt.axvline(brooklyn_median, color='y', linestyle='dotted', linewidth=3, label="median")
plt.axvline(b_mode, color='orange', linestyle='dashed', linewidth=3, label="mode")
plt.legend()
plt.show()

# Plot the figure
plt.hist(manhattan_price, range=(0, 10000),  edgecolor='black')
plt.title("Manhattan 1 Bedroom Price")
plt.xlabel("Cost")
plt.ylabel("Count")
plt.axvline(manhattan_mean, color='r', linestyle='solid', linewidth=2, label="mean")
plt.axvline(manhattan_median, color='y', linestyle='dotted', linewidth=3, label="median")
plt.axvline(m_mode, color='orange', linestyle='dashed', linewidth=3, label="mode")
plt.legend()
plt.show()

# Plot the figure
plt.hist(queens_price, range=(0, 10000),  edgecolor='black')
plt.title("Queens 1 Bedroom Price")
plt.xlabel("Cost")
plt.ylabel("Count")
plt.axvline(queens_mean, color='r', linestyle='solid', linewidth=2, label="mean")
plt.axvline(queens_median, color='y', linestyle='dotted', linewidth=3, label="median")
plt.axvline(q_mode, color='orange', linestyle='dashed', linewidth=3, label="mode")
plt.legend()
plt.show()